### ISSUE TITLE
Camera not opening

### ISSUE THREAD

**Issue by PrudhviGNV** [louiejancevski/FaceEmotionDetector#1]
Hello 
Your project is cool. But while I am trying to  execute it. Camera is not opening .

**Comment by louiejancevski** [comment]
It usually takes a few seconds to open after you've given the right permission from your browser. If you have your camera open somewhere else, it can also give you an error  `DOMException: Could not start video source`. Also, are you using Google Chrome? I just checked and it's working for me, I'm using Version 84.0.4147.125.

**Comment by louiejancevski** [comment]
It usually takes a few seconds to open after you've given the right permission from your browser. If you have your camera opened somewhere else, it can also give you an error  `DOMException: Could not start video source`. Also, are you using Google Chrome? I just checked and it's working for me, I'm using Version 84.0.4147.125.
